version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: careercompass-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: careercompass
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - careercompass-network

  redis:
    image: redis:7.2-alpine
    container_name: careercompass-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - careercompass-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: careercompass-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password@mongodb:27017/careercompass?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - careercompass-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: careercompass-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - careercompass-network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: careercompass-worker
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password@mongodb:27017/careercompass?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - careercompass-network

volumes:
  mongodb_data:
  redis_data:

networks:
  careercompass-network:
    driver: bridge
